port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯ 01ä¸¨1x HK, server: silver-can.steamcommunity.world, port: 12022, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯ 02ä¸¨1x HK, server: silver-can.steamcommunity.world, port: 12023, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯ 03ä¸¨1x HK, server: silver-can.steamcommunity.world, port: 12024, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯å®¶å®½ 01ä¸¨1x HK, server: silver-can.steamcommunity.world, port: 12729, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯å®¶å®½ 02ä¸¨1x HK, server: silver-can.steamcommunity.world, port: 13105, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯å®¶å®½ 03ä¸¨1x HK, server: silver-can.steamcommunity.world, port: 13115, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡¨ğŸ‡³ å°æ¹¾ 01ä¸¨1x TW, server: silver-can.steamcommunity.world, port: 12304, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡¨ğŸ‡³ å°æ¹¾ 02ä¸¨1x TW, server: silver-can.steamcommunity.world, port: 12305, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡¨ğŸ‡³ å°æ¹¾ 03ä¸¨1x TW, server: silver-can.steamcommunity.world, port: 12306, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 01ä¸¨1x SG, server: silver-can.steamcommunity.world, port: 12000, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 02ä¸¨1x SG, server: silver-can.steamcommunity.world, port: 12002, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 03ä¸¨1x SG, server: silver-can.steamcommunity.world, port: 12003, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 01ä¸¨1x JP, server: silver-pvg.steamcommunity.world, port: 12011, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 02ä¸¨1x JP, server: silver-pvg.steamcommunity.world, port: 12010, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 03ä¸¨1x JP, server: silver-pvg.steamcommunity.world, port: 12012, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡¬ğŸ‡§ è‹±å›½ä¸¨1x GB, server: silver-pek.steamcommunity.world, port: 12710, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½-çº½çº¦ 01ä¸¨1x US, server: silver-pvg.steamcommunity.world, port: 13006, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½-çº½çº¦ 02ä¸¨1x US, server: silver-pvg.steamcommunity.world, port: 13005, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½-ä¸¹ä½›ä¸¨1x US, server: silver-pvg.steamcommunity.world, port: 13110, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½-æ´›æ‰çŸ¶ 01ä¸¨1x US, server: silver-pvg.steamcommunity.world, port: 13007, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½-æ´›æ‰çŸ¶ 02ä¸¨1x US, server: silver-pvg.steamcommunity.world, port: 13010, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½-æ´›æ‰çŸ¶ 03ä¸¨1x US, server: silver-pvg.steamcommunity.world, port: 12706, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½-è¿ˆé˜¿å¯†ä¸¨1x US, server: silver-pvg.steamcommunity.world, port: 13109, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½-è¥¿é›…å›¾ä¸¨1x US, server: silver-pvg.steamcommunity.world, port: 13111, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½-å ªè¨æ–¯ä¸¨1x US, server: silver-pvg.steamcommunity.world, port: 13118, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½-èŠåŠ å“¥ä¸¨1x US, server: silver-pvg.steamcommunity.world, port: 13253, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½-å¤æ´›ç‰¹ä¸¨1x US, server: silver-pvg.steamcommunity.world, port: 13257, type: ss, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: f6f5e28d5b73.microsoft.com}, udp: true}

proxy-groups:
  - name: ğŸŠ æ‰‹åŠ¨é€‰æ‹©
    type: select
    proxies:
      - DIRECT  
      - ğŸ‡­ğŸ‡° é¦™æ¸¯ 01ä¸¨1x HK
      - ğŸ‡­ğŸ‡° é¦™æ¸¯ 02ä¸¨1x HK
      - ğŸ‡­ğŸ‡° é¦™æ¸¯ 03ä¸¨1x HK
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 01ä¸¨1x JP
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 02ä¸¨1x JP
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 03ä¸¨1x JP
      - ğŸ‡¨ğŸ‡³ å°æ¹¾ 01ä¸¨1x TW
      - ğŸ‡¨ğŸ‡³ å°æ¹¾ 02ä¸¨1x TW
      - ğŸ‡¨ğŸ‡³ å°æ¹¾ 03ä¸¨1x TW
  - name: ğŸ‹ é¦™æ¸¯
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯ 01ä¸¨1x HK
      - ğŸ‡­ğŸ‡° é¦™æ¸¯ 02ä¸¨1x HK
      - ğŸ‡­ğŸ‡° é¦™æ¸¯ 03ä¸¨1x HK
      - ğŸ‡­ğŸ‡° é¦™æ¸¯å®¶å®½ 01ä¸¨1x HK
      - ğŸ‡­ğŸ‡° é¦™æ¸¯å®¶å®½ 02ä¸¨1x HK
      - ğŸ‡­ğŸ‡° é¦™æ¸¯å®¶å®½ 03ä¸¨1x HK
  - name: ğŸ å°æ¹¾
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - ğŸ‡¨ğŸ‡³ å°æ¹¾ 01ä¸¨1x TW
      - ğŸ‡¨ğŸ‡³ å°æ¹¾ 02ä¸¨1x TW
      - ğŸ‡¨ğŸ‡³ å°æ¹¾ 03ä¸¨1x TW
  - name: ğŸŒ æ–°åŠ å¡
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 01ä¸¨1x SG
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 02ä¸¨1x SG
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 03ä¸¨1x SG
  - name: ğŸ¥­ æ—¥æœ¬
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 01ä¸¨1x JP
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 02ä¸¨1x JP
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 03ä¸¨1x JP
  - name: ğŸ è‹±å›½
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - ğŸ‡¬ğŸ‡§ è‹±å›½ä¸¨1x GB
  - name: ğŸ ç¾å›½
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - ğŸ‡ºğŸ‡¸ ç¾å›½-çº½çº¦ 01ä¸¨1x US
      - ğŸ‡ºğŸ‡¸ ç¾å›½-çº½çº¦ 02ä¸¨1x US
      - ğŸ‡ºğŸ‡¸ ç¾å›½-ä¸¹ä½›ä¸¨1x US
      - ğŸ‡ºğŸ‡¸ ç¾å›½-æ´›æ‰çŸ¶ 01ä¸¨1x US
      - ğŸ‡ºğŸ‡¸ ç¾å›½-æ´›æ‰çŸ¶ 02ä¸¨1x US
      - ğŸ‡ºğŸ‡¸ ç¾å›½-æ´›æ‰çŸ¶ 03ä¸¨1x US
      - ğŸ‡ºğŸ‡¸ ç¾å›½-è¿ˆé˜¿å¯†ä¸¨1x US
      - ğŸ‡ºğŸ‡¸ ç¾å›½-è¥¿é›…å›¾ä¸¨1x US
      - ğŸ‡ºğŸ‡¸ ç¾å›½-å ªè¨æ–¯ä¸¨1x US
      - ğŸ‡ºğŸ‡¸ ç¾å›½-èŠåŠ å“¥ä¸¨1x US
      - ğŸ‡ºğŸ‡¸ ç¾å›½-å¤æ´›ç‰¹ä¸¨1x US

rule-providers:
  #åŸºç¡€è§„åˆ™é›†
  applications:
    type: http
    behavior: classical
    url: "https://gitee.com/arpmoc/clash-for-windows-rule-public/raw/master/Rules/Applications.yaml"
    path: ./ruleset/applications.yaml
    interval: 86400
  direct:
    type: http
    behavior: classical
    url: "https://gitee.com/arpmoc/clash-for-windows-rule-public/raw/master/Rules/Direct.yaml"
    path: ./ruleset/direct.yaml
    interval: 86400
  #è½¯ä»¶è§„åˆ™é›†
  google:
    type: http
    behavior: classical
    url: "https://gitee.com/arpmoc/clash-for-windows-rule-public/raw/master/Rules/Google.yaml"
    path: ./ruleset/google.yaml
    interval: 86400
  microsoft:
    type: http
    behavior: classical
    url: "https://gitee.com/arpmoc/clash-for-windows-rule-public/raw/master/Rules/Microsoft.yaml"
    path: ./ruleset/microsoft.yaml
    interval: 86400
  telegram:
    type: http
    behavior: classical
    url: "https://gitee.com/arpmoc/clash-for-windows-rule-public/raw/master/Rules/Telegram.yaml"
    path: ./ruleset/telegram.yaml
    interval: 86400
  tiktok:
    type: http
    behavior: classical
    url: "https://gitee.com/arpmoc/clash-for-windows-rule-public/raw/master/Rules/TikTok.yaml"
    path: ./ruleset/tiktok.yaml
    interval: 86400
  netflix:
    type: http
    behavior: classical
    url: "https://gitee.com/arpmoc/clash-for-windows-rule-public/raw/master/Rules/Netflix.yaml"
    path: ./ruleset/netflix.yaml
    interval: 86400
  copilot:
    type: http
    behavior: classical
    url: "https://gitee.com/arpmoc/clash-for-windows-rule-public/raw/master/Rules/Copilot.yaml"
    path: ./ruleset/copilot.yaml
    interval: 86400


rules:
  #è‡ªå®šä¹‰è§„åˆ™
  
  #è‡ªåŠ¨æ›´æ–°è§„åˆ™
  - RULE-SET,applications,ğŸ å°æ¹¾
  - RULE-SET,direct,DIRECT
  - RULE-SET,google,ğŸ‹ é¦™æ¸¯
  - RULE-SET,telegram,ğŸ ç¾å›½
  - RULE-SET,tiktok,ğŸ¥­ æ—¥æœ¬
  - RULE-SET,netflix,ğŸ‹ é¦™æ¸¯
  - RULE-SET,copilot,ğŸ‹ é¦™æ¸¯
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,ğŸŠ æ‰‹åŠ¨é€‰æ‹©
